### ISSUE TITLE
Add Android and iOS support

### ISSUE THREAD

**Issue by lucor** [lucor/fyne-cross#10]
Initial support for mobile (Android and iOS) has been added into the fyne develop branch (fyne-io/fyne#416) via gomobile. Add support to fyne-cross.

**Comment by joeblew99** [comment]
@lucor  this is great.

Also you can side step gomobile if you want.  I just noticed gomobile sometimes being too smart for its own good and getting in the way.
The code is here:
https://git.sr.ht/~eliasnaur/gio/tree/master/cmd/gio
