### ISSUE TITLE
Building on Clear Linux fails with add user error

### ISSUE THREAD

**Issue by Jacalz** [lucor/fyne-cross#12]
The following error makes it unusable:
```bash
adduser: The UID 0 is already in use.
exit status 1
```

Any help on getting your program to work?

**Comment by lucor** [comment]
It seems you are running the program as root.
Right now fyne-cross does the assumption that it is executed as non-root user.
Could please try with a different user ?

**Comment by lucor** [comment]
Fixed into the develop branch via e5a1921

**Comment by Jacalz** [comment]
I just tested the change and I can confirm that it fixes my use case. Thanks for the solid support and this absolutely great software for compiling for more os/cpu targets. Highly appreciated 👍 

The reason that this had to be done was due to the fact that Clear Linux has some kind of security feature that forces you to use sudo to be able to use docker...
