### ISSUE TITLE
[Feature Request] Add option to build release binaries

### ISSUE THREAD

**Issue by Jacalz** [lucor/fyne-cross#13]
Go binaries are generally quite large and the only way to make them significantly smaller is to strip out the debugging and dwarf data if you don't want to lose any performance. That is done with -ldflags="-s -w" duing package build time.

I would like an option to just pass something like `-release` or `-strip` to build all the resulting cross compiled binaries using that to remove a couple megabytes from each file. If you are sending out a binary to customers, it feels like debug data is unnecessary for most use cases. Those that don't deem it necessary can thus just build without it if they so desire.

**Comment by lucor** [comment]
Binaries are stripped starting from [v1.1.0](https://github.com/lucor/fyne-cross/blob/master/build.go#L334-L338). It is now the default behavior for the reasons you stated above.
Do you think could be useful have an option like `-debug` or similar where these flags are not used?

**Comment by Jacalz** [comment]
Yeah I think that could be a useful option in some cases, especially if there are os/architecture bugs that needs to be debugged.

If the stripping is already in 1.1.0, would you mind adding that to the changelog?

**Comment by lucor** [comment]
Ops, missed that in the changelog. Added into release 1.2.0 along with other changes.

**Comment by Jacalz** [comment]
Wonderful :+1: Thanks for making this wonderful software :slightly_smiling_face:
