### ISSUE TITLE
[Feature Request] Ability to package with an icon using fyne/cmd 

### ISSUE THREAD

**Issue by Jacalz** [lucor/fyne-cross#14]
The cmd for fyne let's users package their applications with a logo to easily have fancy programs with working icons without much hassle, if any at all really. I would love to see a feature here that let's us specify an icon and get packaged versions of all applications (where possible) for all out cross compiled files.

**Comment by lucor** [comment]
Agreed, this is a nice to have. As now integrating the `fyne` command should be the best way to achieve this, at least for desktop.

**Comment by Jacalz** [comment]
This would be amazing and amazingly useful, especially for building windows binaries. At the moment, I am basically running fyne cross twice to get a binary, package the icon using the fyne cmd tool and lastly running the compile once again for windows. This takes a lot of time which this feature should be able to hopefully do in one go.

The fyne cmd utility tries to rebuild after running the compile, but without local windows compiler toolchains it just fails. this is what we have fyne-cross for...

**Comment by lucor** [comment]
A possible solution could be:
- use the cmd/fyne command to create linux and darwin packages
- use the [mingw32-windres](https://github.com/josephspurrier/goversioninfo#alternatives-to-this-tool) to generate the .syso and then compile. In this way we'd able to compile only one time.
- add as requirement that an `Icon.png` must be located under the project root
- output the packages into the `build` package folder too

Thoughts?

**Comment by Jacalz** [comment]
I think generating the .syso file directly and just compiling once makes a lot of sense. I don’t think it should require that Icon file, a —icon flag to specify an icon path to use. I am thinking of something like this:
```bash
fyne-cross —targets=windows/amd64,darwin/amd64,linux/amd64 —icon assets/icon-512.png
```

**Comment by lucor** [comment]
Available on develop for testing.

**Comment by Jacalz** [comment]
Testing this right now and getting the following output when running `sudo ~/go/bin/fyne-cross --targets=windows/amd64,darwin/amd64,linux/amd64 -dist -icon assets/icon-512.png --output=sparta`:
```
Project root dir: /home/jacob/go/src/sparta
Package dir: .
Build output folder: /home/jacob/go/src/sparta/build
Dist mode enabled true
Icon app: assets/icon-512.png
Dist output folder: /home/jacob/go/src/sparta/dist
Target windows/amd64
/usr/local/bin/docker-entrypoint.sh: 1: exec: gowindres: not found
exit status 127
```

**Comment by lucor** [comment]
Ops, the build for the develop image on docker hub was not triggered... now the [new image should be available](https://hub.docker.com/layers/lucor/fyne-cross/develop/images/sha256-2305e5cc8a15aaf518d6c5fb2b32c81dcfa6565563f059fa362f5e88494c2377). Could you please try again ?

**Comment by Jacalz** [comment]
I am running in to the exact same error again unfortunately. It still says `/usr/local/bin/docker-entrypoint.sh: 1: exec: gowindres: not found`.

**Comment by lucor** [comment]
I think for some reasons the docker image is not the last. The Image ID for `lucor/fyne-cross:develop` using `docker images` should be `decbb495622b`. If not could you please update manually the image with `docker pull` ?

Btw there is also a fix about using custom icon (3b95d4f) so please be sure you have the fyne-cross binany updated too.

**Comment by Jacalz** [comment]
It seems to work fine. I have only tested the Windows binary and it does successfully get the correct icon. Only thing that I don't like is all the objects that get placed inside the folder:
![image](https://user-images.githubusercontent.com/25466657/74243432-08aa8680-4ce0-11ea-817c-9129796e3be2.png)
I see little reason to save  `main.rc`, `usr`, `sparta.syso`, `sparta.ico` and `sparta.exe manifest` inside my source folder. See these files above, I think you can agree that it is a bit annoying.

I get that we get the dist files inside the dist folder and regular files inside build, I appreciate that. Only weird thing there is that the windows exe with icon is placed inside the build folder and not dist.
![image](https://user-images.githubusercontent.com/25466657/74243982-0268da00-4ce1-11ea-90ef-776cfe57df4b.png)

You can ignore that some files are locked, that is because I need to run docker containers using sudo.

**Comment by lucor** [comment]
Happy to see it worked ;-)

Agree with you, a little re-thinking about the fyne-cross output is planned... this is way you still found that files around :-)

One of the ideas that comes in mind is to have a dedicated folder under the project root like fyne-cross where the tool can operate without conflict with the project itself... but I'll track this into another issue for discussion.

**Comment by lucor** [comment]
For reference: created #38

**Comment by Jacalz** [comment]
How can I specify the appID for the dist packaging. I believe the MacOS binaries can use that right?

**Comment by lucor** [comment]
It is not supported at the moment. Do you mind to open an issue about appID support ? Thanks!

**Comment by Jacalz** [comment]
Sure. Will do :)

**Comment by Jacalz** [comment]
Testing this on develop and it seems to work as expected. goo job :+1:
