### ISSUE TITLE
Add wildcard support for goarch

### ISSUE THREAD

**Issue by lucor** [lucor/fyne-cross#15]
In order to compile all supported GOARCH for a specified GOOS we have to specify all combinations.
For example to compile for all supported GOARCH on linux:
`--targets=linux/amd64,linux/arm64,linux/386,linux/arm`

Adding support for wildcard will make the command more usable in this case: 
`--targets=linux/*`

**Comment by diptag** [comment]
I would like to take this up.

**Comment by lucor** [comment]
Added in #17
