### ISSUE TITLE
Unable to find image 'lucor/fyne-cross:1.2.2' locally

### ISSUE THREAD

**Issue by Merith-TK** [lucor/fyne-cross#21]
`fyne-cross --targets="windows/amd64" --output=HelloWorld.exe HelloWorld.go`
```
Unable to find image 'lucor/fyne-cross:1.2.2' locally
docker: Error response from daemon: manifest for lucor/fyne-cross:1.2.2 not found: manifest unknown: manifest unknown.
See 'docker run --help'.
exit status 125
```
Same setup, but docker actually started to work with the new release
```
[developer@archlinux fyne-projects]$ fyne-cross -version
fyne-cross version 1.2.2
```

**Comment by lucor** [comment]
> `fyne-cross --targets="windows/amd64" --output=HelloWorld.exe HelloWorld.go`
> 
> ```
> Unable to find image 'lucor/fyne-cross:1.2.2' locally
> docker: Error response from daemon: manifest for lucor/fyne-cross:1.2.2 not found: manifest unknown: manifest unknown.
> See 'docker run --help'.
> exit status 125
> ```

Apologies, it was a configuration error on dockerhub that has created the image with a wrong tag.
Now should be everything ok.

> Same setup, but docker actually started to work with the new release
> 
> ```
> [developer@archlinux fyne-projects]$ fyne-cross -version
> fyne-cross version 1.2.2
> ```

The command `fyne-cross -version` does not use docker so it'd have worked also in previous version.

**Comment by Merith-TK** [comment]
Works like a charm now, if i have any more issues, i will tell you
