### ISSUE TITLE
Unable to build target windows/amd64

### ISSUE THREAD

**Issue by Merith-TK** [lucor/fyne-cross#31]
```
[developer@archlinux Wallpaper]$ fyne-cross --targets=windows/amd64
Build output folder: /Workspace/Personal-Projects/Wallpaper/build
Target windows/amd64
Building...
# wallpaper
/usr/local/go/pkg/tool/linux_amd64/link: running x86_64-w64-mingw32-gcc failed: exit status 1
/usr/bin/x86_64-w64-mingw32-ld: i386 architecture of input file `/tmp/go-link-798816917/000000.o' is incompatible with i386:x86-64 output
collect2: error: ld returned 1 exit status

exit status 2
```
```
package main

import (
        "fyne.io/fyne/app"
        "fyne.io/fyne/widget"
)

func main() {
        a := app.New()

        w := a.NewWindow("Wallpaper")
        w.SetContent(widget.NewVBox(
                widget.NewLabel("Select your wallpaper"),
                widget.NewButton("Cancel", func() {
                        a.Quit()
                }),
        ))

        w.ShowAndRun()
}
```

unable to compile

**Comment by lucor** [comment]
Could you please report the version of fyne-cross?
I'm unable to replicate with the latest one (1.3.0).

**Comment by Merith-TK** [comment]
[developer@archlinux ~]$ fyne-cross --version
fyne-cross version 1.3.0


Latest.

**Comment by lucor** [comment]
Thanks. Could you please also send the verbose output ?
`fyne-cross --targets=windows/amd64 -v`

**Comment by Merith-TK** [comment]
https://pastebin.com/zynFVwCm
Note, it took upwards of two minutes sitting at os/exec

**Comment by lucor** [comment]
The only strange thing I can see in the log is the `build/wallpaper.fyne-windows-amd64.exe` should nto contain the `.` unless you have specified it using the `--output` flag.

It'd great if you have a chance to test against the develop branch (just updated) after cleaning the cache folder `/home/developer/.cache/fyne-cross`.

Btw, which OS / version are you using?

With regard to the waiting time at os/exec it is due to packages compilation for the stdlib for the architecture. We'd have precompiled them into the docker image but this will increase the image size.

**Comment by Merith-TK** [comment]
Host is Archlinux.

The repo is at
https://cdn.merith.tk/?dir=workspace/Personal-Projects/Wallpaper

If you want to take a look.

**Comment by lucor** [comment]
The problem is due to the file `rsrc.syso` that is compiled for 386 hence the linker's error.
```
file  rsrc.syso
rsrc.syso: Intel 80386 COFF object file, no line number info, not stripped, 1 section, symbol offset=0x14b5, 1 symbols
```

To run the example above simply remove this file.

If you want to use it in your project need to re-compile against amd64.
Btw, build of your repo project against window/386 works correctly.

**Comment by Merith-TK** [comment]
Huh, interesting, thanks for the info, will try to recompile that syso file
for amd64, thanks.
Working off email because on train right now so you can close this if you
want, maybe put it in FAQ that this can be an issue to some people

**Comment by lucor** [comment]
Going to close.
Please note that you'll have same error also building without fyne-cross if the target is not windows/386.
This for example is on my linux machine:
```
go build 
...
# wallpaper
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: i386 architecture of input file `/tmp/go-link-513426974/000000.o' is incompatible with i386:x86-64 output
collect2: error: ld returned 1 exit status
```
