### ISSUE TITLE
Package android files as .apk

### ISSUE THREAD

**Issue by Jacalz** [lucor/fyne-cross#37]
Right now it seems that the android builds are only .so files and not .apk files. it would be great if this could be achieved to make life easier for people building for android. I for example have no idea on how to install a .so file on an android phone and run the app..

**Comment by lucor** [comment]
To generate the apk we need fyne package command supports go modules fyne-io/fyne#660

**Comment by lucor** [comment]
Available on develop for testing

**Comment by Jacalz** [comment]
I sadly don't really own any Android devices. Will see if I can borrow a friends phone and test this sometime in the coming week :)

**Comment by Jacalz** [comment]
Sorry for the late testing, but I am getting this on building:
```go
Status: Downloaded newer image for lucor/fyne-cross:develop-android
go [-e -json -compiled=true -test=false -export=false -deps=false -find=true -- .]: exit status 2: go: downloading golang.org/x/mobile v0.0.0-20190719004257-d2bd2a29d028
go: extracting golang.org/x/mobile v0.0.0-20190719004257-d2bd2a29d028
go: finding golang.org/x/net latest
go: downloading golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e
go: extracting golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e
# runtime/cgo
gcc: error: unrecognized command line option '-marm'; did you mean '-mabm'?

Could not package the Fyne app: exit status 1
```

**Comment by lucor** [comment]
@Jacalz good catch thanks. Indeed the docker android image need to be updated in order to support the upcoming version of fyne (v1.2.4). Current version should work against v1.2.3.

The image should be updated in next days, looking if we can update the base image to go v1.14 too :)

In the meantime, as temporary fix, installing the latest fyne cli command into the android docker image should fix:
```
cat <<EOF > Dockerfile
FROM lucor/fyne-cross:develop-android

# fyne release/v1.2.4 branch
# install fyne cli from the release/v1.2.4 branch
RUN GO111MODULE=on go get -v "fyne.io/fyne/cmd/fyne@79fe7824d3ae53b16019b1a7ffcf17fb6cfe217d"
RUN mv /go/bin/fyne /usr/local/bin
EOF

docker build -t  lucor/fyne-cross:develop-android .
```
