### ISSUE TITLE
Introduce a root folder and layout for fyne-cross output

### ISSUE THREAD

**Issue by lucor** [lucor/fyne-cross#38]
fyne-cross could generates several files and folders when building and packaging fyne apps.
Introducing a unique root folder for fyne-cross should allow to:
- avoid any possible conflict with the existing resources for the project layout we are going to build;
- ignore the fyne-cross resources for a VCS (i.e. adding the root folder to a .gitignore file)

A possible layout could be:
```
project-root
├── main.go
├── go.mod
├── go.sum
├── ......
├── fyne-cross //fyne-cross root dir
│   └── bin  // will contains the binaries
│   └── dist // will contains the distribution packages
│   └── tmp // will be use to store temporary resources used to build binaries and packages
```

**Comment by Jacalz** [comment]
Sounds like a great improvement 👍

**Comment by lucor** [comment]
Available in development for testing

**Comment by Jacalz** [comment]
This works really well and seems to speed up cross compiling a huge deal for me. The whole folder is created with the sudo user (since a lot of distros need docker to run under sudo) and thus I always need change the permissions, but otherwise perfect :+1:

**Comment by lucor** [comment]
Wrt permission issue I don't recall if we discussed this already but if is a on option for you adding the used to docker group would allow to not use sudo: https://docs.docker.com/install/linux/linux-postinstall/
