### ISSUE TITLE
can not  pull lucor/fyne-cross:1.3.2

### ISSUE THREAD

**Issue by tianxia0079** [lucor/fyne-cross#39]
just can pull docker pull lucor/fyne-cross:latest

suggest：update build.go ,const version = "1.3.2"
to :
const version = "latest"

**Comment by tianxia0079** [comment]
how to build fyne-cross by self.thanks

**Comment by lucor** [comment]
Hi @tianxia0079  

> can not pull lucor/fyne-cross:1.3.2
> just can pull docker pull lucor/fyne-cross:latest

which kind of error are you getting using fyne-cross? 
Do you get any error using directly `docker pull lucor/fyne-cross:1.3.2` ?

> suggest：update build.go ,const version = "1.3.2"
> to :
> const version = "latest"

The version in build.go is used to keep track of the used image in fyne-cross ensuring old versions of the tool will always work.

> how to build fyne-cross by self

To build the project yourself, clone the repo and run `go build -o fyne-cross`. 
Note: requires go >1.12 and go module enabled.

**Comment by tianxia0079** [comment]
@lucor
thanks!

**Comment by tianxia0079** [comment]
@lucor
[root@localhost fyne-cross]# go build -o fyne-cross
# runtime/internal/sys
compile: version "go1.13.8" does not match go tool version "go1.12.12"
# unicode/utf8
compile: version "go1.13.8" does not match go tool version "go1.12.12"
# unicode
compile: version "go1.13.8" does not match go tool version "go1.12.12"
# math/bits
compile: version "go1.13.8" does not match go tool version "go1.12.12"
# internal/race
compile: version "go1.13.8" does not match go tool version "go1.12.12"
# internal/goversion
compile: version "go1.13.8" does not match go tool version "go1.12.12"
# internal/cpu
compile: version "go1.13.8" does not match go tool version "go1.12.12"
# sync/atomic
compile: version "go1.13.8" does not match go tool version "go1.12.12"
# runtime/internal/atomic
compile: version "go1.13.8" does not match go tool version "go1.12.12"
# runtime/cgo
compile: version "go1.13.8" does not match go tool version "go1.12.12"

how to deal this error,thanks
