### ISSUE TITLE
Add support for Go 1.13

### ISSUE THREAD

**Issue by pymq** [lucor/fyne-cross#46]
Hi! Recently encountered a problem of building an application with a version other than 1.12, so I had to build manually from a target os. Is it possible to add an option to specify which version of go compiler to use?

As I can see docker/golang-cross#39 won't/can't add versions other than 1.12 for OS X - maybe its worth it to add support for new versions to other OS? There is also new version coming soon.

**Comment by lucor** [comment]
Right now we rely on docker/golang-cross so we need to wait for a new version that supports a newer version of Go (see also: docker/golang-cross/pull/45)

By the way I'm wondering if could make sense to have fyne-cross download xcode and generate locally the image for darwin. 
This will require an apple developer account but will reduce the time supporting newer versions of Go and remove the need to host an xcode image.

What do you think ?

cc @Jacalz I know is interested about 1.13 too

**Comment by Jacalz** [comment]
Yes indeed I am. I find it absolutely absurd that it takes this amount of time to get it updated upstream.

@lucor I don't know, but I think that that local download of xcode won't be a good solution. Xcode (talking about the whole AppStore download) is about 20GB download and how that would work on a computer not running MacOS, seems to bit hard. Apple developer accounts cost money, so it would make it a lot harder for users to use it. 

Perhaps https://github.com/elastic/golang-crossbuild could be looked at for providing the image?

**Comment by pymq** [comment]
Seems like they recently merged docker/golang-cross#53 with 1.13 support!
Although it has no support for OS X it would be great to have an option in fyne-cross to use newer versions for supported platforms.

**Comment by lucor** [comment]
Just landed in develop for testing :-)

**Comment by pymq** [comment]
Ah, now I see it, thanks!

**Comment by Jacalz** [comment]
I have tested this on develop and Go 1.13.8 does not seem to cause any issues for me...

**Comment by lucor** [comment]
@Jacalz happy to hear that :)
I was able to test the generated binary on OS X 10.11.6 (El Capitan)  and it seems to work without issues too.
Going to close, feel free to reopen a create new issue if any problem arise.
