### ISSUE TITLE
how to set icon 

### ISSUE THREAD

**Issue by tianxia0079** [lucor/fyne-cross#47]
fyne-cross --targets=linux/amd64,windows/amd64,darwin/amd64
how to set icon

**Comment by lucor** [comment]
That feature is available in develop for testing.
After installed the dev version, you have two ways:
a) Using an `Icon.png` into the project root:
`fyne-cross --targets=linux/amd64,windows/amd64,darwin/amd64 --dist` 
b) Using png into a custom location:
`fyne-cross --targets=linux/amd64,windows/amd64,darwin/amd64 --dist --icon=assest/icon.png` 

Related to #14

**Comment by lucor** [comment]
Just released v1.4.0 that allow to add an icon:

`fyne-cross --targets=linux/amd64,windows/amd64,darwin/amd64 --icon=assest/icon.png`

**Comment by lucor** [comment]
Available in the latest release, going to close. Please feel free to re-open if any issue arise.
