### ISSUE TITLE
MacOS dist packaging should have separate name

### ISSUE THREAD

**Issue by Jacalz** [lucor/fyne-cross#48]
Building with the dist packaging support in develop creates the application with a name in the pattern of `name-darwin-amd64.app`. This is far from practical as nobody would want their distribution binary have `*-darwin-amd64` in their name when it shows up in launchpad.

I suggest that a flag is provided `-appName` that lets the user set the application name in the MacOS packaging. My app would then be called Sparta.app instead of `sparta-darwin-amd64.app`.

**Comment by lucor** [comment]
Agreed, it is a good point.
Modified the output to not contain the OS and Arch info and store them under a dedicated folder like:
```
fyne-cross
│   ├── bin
│   │   ├── darwin-amd64
│   │   │   └── Sparta
│   │   ├── linux-amd64
│   │   │   └── Sparta
│   │   └── windows-amd64
│   │       └── Sparta.exe
│   ├── dist
│   │   ├── darwin-amd64
│   │   │   └── Sparta.app
│   │   ├── linux-amd64
│   │   │   └── Sparta.tar.gz
│   │   └── windows-amd64
│   │       └── Sparta.exe
```
in this way we'd use the --output flag to specify the app name.
Please note that the fix also remove the need to specify the `--dist` flag, by default now fyne-cross will generate also the dist packages :)

**Comment by Jacalz** [comment]
Thanks for the quick fix. I have tested it and it seems to work great :+1:
