### ISSUE TITLE
Dist packaged linux binaries seem to include two binaries

### ISSUE THREAD

**Issue by Jacalz** [lucor/fyne-cross#50]
Running a dist compile seems to result in two binaries being created, both the name and the regular one. Please see the screenshots below:

### Binaries are doubled (leading to huge tar file size):

![image](https://user-images.githubusercontent.com/25466657/76167740-4b3d7280-6169-11ea-9f31-3d96c6df7577.png)

### Desktop files are also double:

![image](https://user-images.githubusercontent.com/25466657/76167789-a707fb80-6169-11ea-93b8-98d5132a0358.png)

### Icons too:

![image](https://user-images.githubusercontent.com/25466657/76167798-b71fdb00-6169-11ea-8f99-b515762f65e8.png)

I am sorry that I didn't catch this in my earlier testing, I was way too focused on getting my MacOS binary to work :-1:

**Comment by lucor** [comment]
It looks like something related to old build output... 
Could you please remove the fyne-cross folder and try again ?
If the error still persist, could you please paste the command you are running?

**Comment by Jacalz** [comment]
You are correct. Looks like something weird happened on my end...
