### ISSUE TITLE
Cross compile from macOS 10.15 to Windows 10

### ISSUE THREAD

**Issue by dwllnet** [lucor/fyne-cross#51]
Running the following command on a clone of https://github.com/fyne-io/examples/ results in a windows executable file. But when I move the file over to Windows 10, it doesn't run. Any idea where to start looking?

fyne-cross --targets=windows/amd64 -v ./main.go 
Project root dir: /git/examples
Package dir: ./main.go
Bin output folder: /git/examples/fyne-cross/bin
Dist output folder:  /git/examples/fyne-cross/dist
[WARN] Icon app was not specified with --icon and a default one was not found at "/git/examples/Icon.png". Using Fyne logo as icon app for testing purpose
Icon app:  /git/examples/fyne-cross/tmp/fyne.png
Building for target windows/amd64
go.mod found
Target windows/amd64 [OK]

**Comment by lucor** [comment]
@dwllnet are you by any chance testing inside a virtual machine ?
If so, this issue: fyne-io/fyne#410 could help to fix.

**Comment by dwllnet** [comment]
You are correct, VirtualBox 6.1.4,  MSEdge Win10 image from  MS. 
Tried just enabling 3D acceleration, did not work.
Increase video memory to 128M, did not work. 
Reinstall VBox Guest Additions after setting the above, which I believe installs the required OpenGL libraries.
Now the examples and my application work perfectly. 

Thanks for pointing me in the right direct.
Also, thanks for writing/supporting fyne-cross, great app.
