### ISSUE TITLE
Allow the user to pass the environment variables to the docker?

### ISSUE THREAD

**Issue by xgfone** [lucor/fyne-cross#59]
I cannot access the domain `*.golang.org`. 

How can I tell fyne-cross to pass the environment variables like `GOSUMDB` and `GORPOXY` to the docker container?

**Comment by lucor** [comment]
This feature is not supported yet, it is planned for the upcoming 2.0.

Assuming you are using latest fyne-cross version (v1.5.0), in the meantime you could "extend" the docker image like:

```
cat <<EOF > Dockerfile
FROM lucor/fyne-cross:1.5.0
ENV GOSUMDB=<yourvalue>
ENV GOPROXY=<yourvalue>
EOF

docker build -t  lucor/fyne-cross:1.5.0 .
```

**Comment by xgfone** [comment]
Yes, I did it like this. EXPECT 2.0!
