### ISSUE TITLE
GOPROXY support

### ISSUE THREAD

**Issue by ElonH** [lucor/fyne-cross#76]
Is there a way to change the environment `GOPROXY` in docker

**Comment by lucor** [comment]
It is possible to specify an env variable into the docker container using the `--env` flag, like:
```
fyne-cross linux --env GOPROXY=<your_proxy>
```

Multiple variables can be specified too:
```
fyne-cross linux --env KEY1=VALUE1 --env KEY2=VALUE2
```

**Comment by ElonH** [comment]
Thank! It saved my lots of time.
