### ISSUE TITLE
iOS fails with "only on darwin" when on mac

### ISSUE THREAD

**Issue by alevinetx** [lucor/fyne-cross#78]
When running ```fyne-cross ios``` on a mac, I'm getting a failure message:

```[✗] iOS build is supported only on darwin hosts```

Looking at https://github.com/lucor/fyne-cross/blob/master/internal/command/ios.go#L193

Should this be ```!=``` instead?

```
	if runtime.GOOS == darwinOS {
		return Context{}, fmt.Errorf("iOS build is supported only on darwin hosts")
	}
```

**Comment by lucor** [comment]
Good catch, thanks.
Fixed in develop.
